Figures for Labeled Optimal PARTitioning paper, [[https://arxiv.org/abs/2006.13967][arXiv:2006.13967]].

- Figure 1: example data and cost computation. [[file:figure-signal-cost.R][R script]], [[file:figure-signal-cost-standAlone.pdf][standAlone
  pdf]], [[file:figure-signal-cost.tex][tex for inclusion in paper]].
- Figure 2: timings. [[file:figure-timings.R][R script]], tex for inclusion in paper: [[file:figure-timings-labels.tex][time vs
  number of labels (left)]], [[file:figure-timings.tex][time vs number of data (right)]].
- Figures 3-4: Best case label error. [[file:figure-label-errors.R][R script]], [[file:figure-label-errors.pdf][OPART pdf (Fig 3
  left)]], [[file:figure-label-errors-BinSeg.pdf][BinSeg pdf (Fig 3 right)]], [[file:figure-label-errors-SegAnnot.pdf][SegAnnot pdf (Fig 4)]].
- Comparison with BIC figures. [[file:figure-cv-BIC.R][R script]]:
  - Figure 5: [[file:figure-cv-BIC.pdf][Error rates]].
  - Figure 6: [[file:figure-cv-BIC-roc.pdf][ROC curves]].

Reproducibility: use "make" with one of the recipes defined in
[[file:Makefile]].

** Presentation slides

[[https://www.youtube.com/watch?v=lm_6_33zOWc][Video screencast]] for NAU ML group meeting, 31 Aug 2020.

[[file:slides.tex]] makes [[file:slides.pdf]]

- [[file:figure-candidates.R]] demo slides.
- [[file:figure-candidates-interactive.R]] creates a more interactive
  version of the demo slide figures, where you can select any t,tau
  and other penalty values:
  [[http://members.cbio.mines-paristech.fr/~thocking/figure-candidates-interactive/]]
- [[file:figure-baselines.R]] makes figures that show why previous
  baselines are not good enough.

** Additional analyses

- Predicted constant penalty label error figures. [[file:figure-cv.R][R script]], [[file:figure-cv.pdf][OPART pdf]],
  [[file:figure-cv-SegAnnot.pdf][SegAnnot pdf]], [[file:figure-cv-roc.pdf][ROC curves]].
- Sequential cross-validation (fold 1 = first half of labels, fold 2 =
  second half labels) figures. [[file:figure-sequence-cv.R][R script]], [[file:figure-sequence-cv-OPART.pdf][Best case OPART differences]],
  [[file:figure-sequence-cv-SegAnnot.pdf][Best case SegAnnot differences]], [[file:figure-sequence-cv-roc.pdf][ROC curves]], [[file:figure-sequence-cv.pdf][Test error rates]].

** Benchmark data set

The 413 real genomic data sequences described in the paper are downloadable here:
- Each CSV file has a sequenceID column which is of the form A.B where
  A is the profile ID number and B is the chromosome name. This ID can
  be used to separate the data into different segmentation/changepoint
  detection problems.
- [[https://github.com/tdhock/LOPART-paper/raw/master/data-for-LOPART-signals.csv.gz][signals]], from 39 to 43628 observations per data sequence.
  - data.i column ranges from 1 to the number of data on that
    sequenceID. (data.i=1 is the first data point in the sequence,
    data.i=2 is the second, etc)
  - logratio column is the raw/noisy data which should be used as
    input to the segmentation/changepoint detection algorithm.
- [[https://github.com/tdhock/LOPART-paper/raw/master/data-for-LOPART-labels.csv.gz][labels]], from 2 to 12 per data sequence.
  - changes column is either 0 or 1 (the number of changepoints which
    should be predicted in this region label). 
    - False positive label is when predicted number of changepoints is
      greater than labeled number of changepoints (e.g., 2 changes
      predicted in either a 0 or 1 label).
    - False negative label is when changes=1 and predicted number of
      changepoints is 0.
  - fold column is either 1 or 2 (fold IDs used in
    cross-validation in the paper).
  - start/end columns define a region of the correponding data
    sequence (in terms of data.i index values) in which the labeled
    number of changes should be detected.
- Note on data source: they were created using SegAnnDB software, in
  which expert biologists looked at scatterplots and created labels
  based on visual interpretation of significant signal/noise
  patterns. [[http://members.cbio.mines-paristech.fr/~thocking/neuroblastoma/signal.list.annotation.sets.RData][Source data file]], [[https://github.com/tdhock/LabeledFPOP-paper/blob/master/signal.list.annotation.sets.R][R Script to process]], [[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4029035/][SegAnnDB paper]].
  
I recommend computing the label error using [[https://github.com/tdhock/penaltyLearning][penaltyLearning]] R package,
[[https://github.com/tdhock/change-tutorial][useR
2017 tutorial materials]].
